use_frameworks!

target 'SwiftAudio_Example' do
 pod 'SwiftAudioEx', :path => '../'

  target 'SwiftAudio_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.1'
    pod 'Nimble' , '~> 10.0.0'

  end
end